/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  genai: [{type: 'autogenerated', dirName: 'gen-ai'}],
  blueprints: [{type: 'autogenerated', dirName: 'blueprints'}],
  bestpractices: [{type: 'autogenerated', dirName: 'bestpractices'}],
  //benchmarks: [{type: 'autogenerated', dirName: 'benchmarks'}],
  resources: [{type: 'autogenerated', dirName: 'resources'}],
  benchmarks: [
    'benchmarks/introduction',
    'benchmarks/price_performance',
    'benchmarks/benchmarking_variables',
    {
      type: 'category',
      label: 'Running your Benchmark',
      items: ['benchmarks/Running/setting_up_environment','benchmarks/Running/benchmarking_checklist'],
    },
        {
      type: 'category',
      label: 'Analyzing your Benchmark',
      items: ['benchmarks/Analyzing/retrieve_event_logs','benchmarks/Analyzing/read_spark_UI'],
    },
        {
      type: 'category',
      label: 'Resources',
      items: ['benchmarks/Resources/Benchmark_results','benchmarks/Resources/Utilities'],
    },    
  ],

};

export default sidebars;
